import { Inter } from "next/font/google";
import "./globals.css";
import { Oswald, MonteCarlo } from "next/font/google";
import local from "next/font/local";
import Navbar from "../components/navbar";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });
const satoshi = local({
  src: [
    {
      path: "../../public/fonts/Satoshi-Variable.ttf",
      weight: "400",
    },
  ],
  variable: "--font-satoshi",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  weight: ["400", "500", "600"],
});

const monteCarlo = MonteCarlo({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-monteCarlo",
});
export const metadata = {
  title: "kalyan kumar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${monteCarlo.variable} ${satoshi.variable} bg-gray-900`}
      >
        <div className="bubble-container">
          {Array.from({ length: 10 }, (_, i) => (
            <div key={i} className="bubble"></div>
          ))}
        </div>
        <Toaster position="top-center" richColors />
        <Navbar />
        <main className="pt-20 md:pt-24">
          {children}
        </main>
      </body>
    </html>
  );
}
